### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by suspectykt** [partiusfabaa/cs2-MiniAdmin#24]
!kick (player_name)
2023-11-23 11:01:23.807 +09:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The input string 'estriper' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at MiniAdmin.MiniAdmin.OnCmdKick(CCSPlayerController controller, CommandInfo command)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass35_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 226
   at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
2023-11-23 11:01:35.585 +09:00 [INFO] (cssharp:Core) CounterStrikeSharp is starting up...

**Comment by partiusfabaa** [comment]
![image](https://github.com/partiusfabaa/cs2-MiniAdmin/assets/96542489/72444631-e1b8-4c5c-b008-6860d3ca55a1)
You can't kick a player by name
