### ISSUE TITLE
css_who errors

### ISSUE THREAD

**Issue by panikajo** [partiusfabaa/cs2-MiniAdmin#3]
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Data.DataException: Error parsing column 4 (EndTime=11/5/2023 11:43:29 PM - DateTime)
 ---> System.InvalidCastException: Unable to convert MySQL date/time to System.DateTime, set AllowZeroDateTime=True or ConvertZeroDateTime=True in the connection string. See https://mysqlconnector.net/connection-options/
   at MySqlConnector.ColumnReaders.TextDateTimeColumnReader.ParseDateTime(ReadOnlySpan`1 data, Boolean convertZeroDateTime, Boolean allowZeroDateTime, DateTimeKind dateTimeKind) in /_/src/MySqlConnector/ColumnReaders/TextDateTimeColumnReader.cs:line 40
   at MySqlConnector.Core.Row.GetValue(Int32 ordinal) in /_/src/MySqlConnector/Core/Row.cs:line 95
   at Deserialize78704a3e-e7b1-4e37-9d53-98bfbdf515d7(DbDataReader)
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3911
   at Deserialize78704a3e-e7b1-4e37-9d53-98bfbdf515d7(DbDataReader)
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1288
   at MiniAdmin.MiniAdmin.IsAdmin(CCSPlayerController controller)
   at MiniAdmin.MiniAdmin.OnCmdWho(CCSPlayerController controller, CommandInfo command)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass31_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 159
   at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 70
`

**Comment by josesupe** [comment]
same problem here
