### ISSUE TITLE
css_who error 

### ISSUE THREAD

**Issue by josesupe** [partiusfabaa/cs2-MiniAdmin#7]
[39;49mSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

---> MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.

at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 449

at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, Action`4 logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 409

at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, Action`4 logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 414

at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 106

at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 135

at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 916

at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 425

at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 387

at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1276

at MiniAdmin.MiniAdmin.IsAdmin(CCSPlayerController controller)

at MiniAdmin.MiniAdmin.OnCmdWho(CCSPlayerController controller, CommandInfo command)

at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass31_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 159

at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)

at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

--- End of inner exception stack trace ---

at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

at System.Delegate.DynamicInvokeImpl(Object[] args)

at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81

**Comment by partiusfabaa** [comment]
try installing the [latest](https://github.com/partiusfabaa/cs2-MiniAdmin/releases/tag/v1.0.4) version

**Comment by panikajo** [comment]
> try installing the [latest](https://github.com/partiusfabaa/cs2-MiniAdmin/releases/tag/fix) version

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Data.DataException: Error parsing column 3 (StartTime=11/5/2023 11:43:29 PM - DateTime)
 ---> System.InvalidCastException: Invalid cast from 'DateTime' to 'Int32'.
   at System.DateTime.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Deserializea7a62933-a0e3-4dd7-8b2c-7ae15e390b02(DbDataReader)
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3911
   at Deserializea7a62933-a0e3-4dd7-8b2c-7ae15e390b02(DbDataReader)
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1288
   at MiniAdmin.MiniAdmin.IsAdmin(CCSPlayerController controller)
   at MiniAdmin.MiniAdmin.OnCmdWho(CCSPlayerController controller, CommandInfo command)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass31_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 159
   at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81

**Comment by partiusfabaa** [comment]
Does it only happen when you write css_who?

**Comment by partiusfabaa** [comment]
> > try installing the [latest](https://github.com/partiusfabaa/cs2-MiniAdmin/releases/tag/fix) version
> 
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.DataException: Error parsing column 3 (StartTime=11/5/2023 11:43:29 PM - DateTime) ---> System.InvalidCastException: Invalid cast from 'DateTime' to 'Int32'. at System.DateTime.System.IConvertible.ToInt32(IFormatProvider provider) at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider) at Deserializea7a62933-a0e3-4dd7-8b2c-7ae15e390b02(DbDataReader) --- End of inner exception stack trace --- at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3911 at Deserializea7a62933-a0e3-4dd7-8b2c-7ae15e390b02(DbDataReader) at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1288 at MiniAdmin.MiniAdmin.IsAdmin(CCSPlayerController controller) at MiniAdmin.MiniAdmin.OnCmdWho(CCSPlayerController controller, CommandInfo command) at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass31_0.b__0(Int32 i, IntPtr ptr) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 159 at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*) at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) --- End of inner exception stack trace --- at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Delegate.DynamicInvokeImpl(Object[] args) at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81

and you deleted the old database?

**Comment by josesupe** [comment]
first error fixed but now i have this error, deleted the database and restarted server after updating


System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

---> System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<CounterStrikeSharp.API.Core.CCSPlayerController> CounterStrikeSharp.API.Utilities.GetPlayers()'.

at MiniAdmin.MiniAdmin.OnCmdWho(CCSPlayerController controller, CommandInfo command)

at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass31_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 159

at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)

at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

--- End of inner exception stack trace ---

at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

at System.Delegate.DynamicInvokeImpl(Object[] args)

at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81

**Comment by partiusfabaa** [comment]
update the dll to the latest version

**Comment by josesupe** [comment]
deleted all the files and put the new version, still same problem

**Comment by partiusfabaa** [comment]
in the folder?

**Comment by josesupe** [comment]
sorry not folder, in the .json

**Comment by partiusfabaa** [comment]
you have to put your database in there

**Comment by josesupe** [comment]
okay, connected to my database, put myself as admin, but when i put css_who, i still have the same error 

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

---> System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<CounterStrikeSharp.API.Core.CCSPlayerController> CounterStrikeSharp.API.Utilities.GetPlayers()'.

at MiniAdmin.MiniAdmin.OnCmdWho(CCSPlayerController controller, CommandInfo command)

at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass31_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 159

at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)

at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

--- End of inner exception stack trace ---

at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

at System.Delegate.DynamicInvokeImpl(Object[] args)

at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81

**Comment by partiusfabaa** [comment]
You've probably already guessed it. But I will write the following. The error is that you have an old CSSharp DLL, it uses a method that appeared in newer versions.
